In [ ]:
import pandas as pd

In [ ]:
df1=pd.read_csv("/content/justdial.csv")

In [ ]:
df1.head()

,jsx-17aafc05bdbc2ecd href,jsx-c6d65bd74360244a src,jsx-c6d65bd74360244a src 2,jsx-c6d65bd74360244a src 4,jsx-c6d65bd74360244a src 5,jsx-c6d65bd74360244a src 6,jsx-c6d65bd74360244a src 7,jsx-c6d65bd74360244a src 8,jsx-c6d65bd74360244a src 9,jsx-c6d65bd74360244a src 10,...,resultbox_countrate,jdicon src,trusttooltip,locatcity,amenities_tabs,amenities_tabs 2,jsx-17aafc05bdbc2ecd 2,jsx-17aafc05bdbc2ecd 3,font14,font14 2
0,https://www.justdial.com/Pune/Cotmac-Electroni...,"data:image/svg+xml,%3csvg%20xmlns=%27http://ww...",https://images.jdmagicbox.com/v2/comp/def_cont...,https://content.jdmagicbox.com/comp/pune/06/02...,"data:image/svg+xml,%3csvg%20xmlns=%27http://ww...","data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP//...","data:image/svg+xml,%3csvg%20xmlns=%27http://ww...","data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP//...","data:image/svg+xml,%3csvg%20xmlns=%27http://ww...","data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP//...",...,281 Ratings,https://akam.cdn.jdmagicbox.com/images/iconten...,This business Information is verified by Justd...,Pune,Electronic Equipment Dealers,CCTV Installation Services,Show Number,WhatsApp,NaN,NaN
1,https://www.justdial.com/Pune/Smartline-System...,"data:image/svg+xml,%3csvg%20xmlns=%27http://ww...",https://images.jdmagicbox.com/v2/comp/def_cont...,https://content.jdmagicbox.com/comp/pune/k7/02...,"data:image/svg+xml,%3csvg%20xmlns=%27http://ww...","data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP//...","data:image/svg+xml,%3csvg%20xmlns=%27http://ww...","data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP//...","data:image/svg+xml,%3csvg%20xmlns=%27http://ww...","data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP//...",...,163 Ratings,NaN,NaN,Pune,Electronic Goods Manufacturers,Electronic Equipment Manufacturers,Show Number,WhatsApp,23 Years,in Business
2,https://www.justdial.com/Pune/Accurate-Industr...,"data:image/svg+xml,%3csvg%20xmlns=%27http://ww...",https://images.jdmagicbox.com/v2/comp/def_cont...,https://content.jdmagicbox.com/comp/pune/x3/02...,"data:image/svg+xml,%3csvg%20xmlns=%27http://ww...","data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP//...","data:image/svg+xml,%3csvg%20xmlns=%27http://ww...","data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP//...","data:image/svg+xml,%3csvg%20xmlns=%27http://ww...","data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP//...",...,126 Ratings,https://akam.cdn.jdmagicbox.com/images/iconten...,This business Information is verified by Justd...,Pune,Electronic Equipment Manufacturers,Control Panel Manufacturers,Show Number,WhatsApp,26 Years,in Business
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.justdial.com/Pune/Intelux-Electron...,"data:image/svg+xml,%3csvg%20xmlns=%27http://ww...",https://images.jdmagicbox.com/v2/comp/def_cont...,https://content.jdmagicbox.com/v2/comp/pune/x5...,"data:image/svg+xml,%3csvg%20xmlns=%27http://ww...","data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP//...","data:image/svg+xml,%3csvg%20xmlns=%27http://ww...","data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP//...","data:image/svg+xml,%3csvg%20xmlns=%27http://ww...","data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP//...",...,84 Ratings,https://akam.cdn.jdmagicbox.com/images/iconten...,This business Information is verified by Justd...,Pune,Isolation Transformer Manufacturers,Transformer Manufacturers,Show Number,WhatsApp,14 Years,in Business

In [ ]:
df1.columns

Index(['jsx-17aafc05bdbc2ecd href', 'jsx-c6d65bd74360244a src',
       'jsx-c6d65bd74360244a src 2', 'jsx-c6d65bd74360244a src 4',
       'jsx-c6d65bd74360244a src 5', 'jsx-c6d65bd74360244a src 6',
       'jsx-c6d65bd74360244a src 7', 'jsx-c6d65bd74360244a src 8',
       'jsx-c6d65bd74360244a src 9', 'jsx-c6d65bd74360244a src 10',
       'jsx-c6d65bd74360244a', 'jsx-c6d65bd74360244a 2',
       'jsx-c6d65bd74360244a 3', 'jsx-17aafc05bdbc2ecd', 'resultbox_totalrate',
       'resultbox_countrate', 'jdicon src', 'trusttooltip', 'locatcity',
       'amenities_tabs', 'amenities_tabs 2', 'jsx-17aafc05bdbc2ecd 2',
       'jsx-17aafc05bdbc2ecd 3', 'font14', 'font14 2'],
      dtype='object')

In [ ]:
df1[['jsx-c6d65bd74360244a 3', 'jsx-17aafc05bdbc2ecd', 'resultbox_totalrate',
       'resultbox_countrate', 'jdicon src']]

,jsx-c6d65bd74360244a 3,jsx-17aafc05bdbc2ecd,resultbox_totalrate,resultbox_countrate,jdicon src
0,More,Cotmac Electronics Pvt Ltd (Corporate Office),4.1,281 Ratings,https://akam.cdn.jdmagicbox.com/images/iconten...
1,More,Smartline Systems,5.0,163 Ratings,NaN
2,More,Accurate Industrial Controls Pvt Ltd,4.3,126 Ratings,https://akam.cdn.jdmagicbox.com/images/iconten...
3,NaN,NaN,NaN,NaN,NaN
4,More,Intelux Electronics Pvt Ltd,4.3,84 Ratings,https://akam.cdn.jdmagicbox.com/images/iconten...
...,...,...,...,...,...
120,NaN,Kyoritsu Electric (India) Pvt Ltd,5.0,1 Rating,NaN
121,NaN,Sivitek INDIA,5.0,1 Rating,https://akam.cdn.jdmagicbox.com/images/iconten...
122,NaN,Sonic Multitech Pvt Ltd,3.4,14 Ratings,https://akam.cdn.jdmagicbox.com/images/iconten...
123,NaN,Yash Tech Electronics Pvt Ltd,5.0,1 Rating,https://akam.cdn.jdmagicbox.com/images/iconten...
124,NaN,Global Engineering,3.0,1 Rating,NaN

In [ ]:
df1.rename(
    columns={'jsx-17aafc05bdbc2ecd': 'Company_Name'},
    inplace=True)

In [ ]:
df1.columns

Index(['jsx-17aafc05bdbc2ecd href', 'jsx-c6d65bd74360244a src',
       'jsx-c6d65bd74360244a src 2', 'jsx-c6d65bd74360244a src 4',
       'jsx-c6d65bd74360244a src 5', 'jsx-c6d65bd74360244a src 6',
       'jsx-c6d65bd74360244a src 7', 'jsx-c6d65bd74360244a src 8',
       'jsx-c6d65bd74360244a src 9', 'jsx-c6d65bd74360244a src 10',
       'jsx-c6d65bd74360244a', 'jsx-c6d65bd74360244a 2',
       'jsx-c6d65bd74360244a 3', 'Company_Name', 'resultbox_totalrate',
       'resultbox_countrate', 'jdicon src', 'trusttooltip', 'locatcity',
       'amenities_tabs', 'amenities_tabs 2', 'jsx-17aafc05bdbc2ecd 2',
       'jsx-17aafc05bdbc2ecd 3', 'font14', 'font14 2'],
      dtype='object')

In [ ]:
print(df1.head())

In [ ]:
df1.columns = [

    # 1
    'business_url',

    # 2
    'placeholder_svg_image',

    # 3
    'default_category_image',

    # 4
    'business_image',

    # 5
    'placeholder_image_1',

    # 6
    'placeholder_image_2',

    # 7
    'placeholder_image_3',

    # 8
    'placeholder_image_4',

    # 9
    'placeholder_image_5',

    # 10
    'placeholder_image_6',

    # 11
    'ui_element',

    # 12
    'ui_element_2',

    # 13
    'ui_element_3',

    # 14
    'company_name',

    # 15
    'rating',

    # 16
    'rating_count',

    # 17
    'verified_icon',

    # 18
    'verification_status',

    # 19
    'city',

    # 20
    'primary_category',

    # 21
    'secondary_category',

    # 22
    'show_number_button',

    # 23
    'whatsapp_option',

    # 24
    'business_age',

    # 25
    'business_age_label'
]

In [ ]:
df1.head()

,business_url,placeholder_svg_image,default_category_image,business_image,placeholder_image_1,placeholder_image_2,placeholder_image_3,placeholder_image_4,placeholder_image_5,placeholder_image_6,...,rating_count,verified_icon,verification_status,city,primary_category,secondary_category,show_number_button,whatsapp_option,business_age,business_age_label
0,https://www.justdial.com/Pune/Cotmac-Electroni...,"data:image/svg+xml,%3csvg%20xmlns=%27http://ww...",https://images.jdmagicbox.com/v2/comp/def_cont...,https://content.jdmagicbox.com/comp/pune/06/02...,"data:image/svg+xml,%3csvg%20xmlns=%27http://ww...","data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP//...","data:image/svg+xml,%3csvg%20xmlns=%27http://ww...","data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP//...","data:image/svg+xml,%3csvg%20xmlns=%27http://ww...","data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP//...",...,281 Ratings,https://akam.cdn.jdmagicbox.com/images/iconten...,This business Information is verified by Justd...,Pune,Electronic Equipment Dealers,CCTV Installation Services,Show Number,WhatsApp,NaN,NaN
1,https://www.justdial.com/Pune/Smartline-System...,"data:image/svg+xml,%3csvg%20xmlns=%27http://ww...",https://images.jdmagicbox.com/v2/comp/def_cont...,https://content.jdmagicbox.com/comp/pune/k7/02...,"data:image/svg+xml,%3csvg%20xmlns=%27http://ww...","data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP//...","data:image/svg+xml,%3csvg%20xmlns=%27http://ww...","data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP//...","data:image/svg+xml,%3csvg%20xmlns=%27http://ww...","data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP//...",...,163 Ratings,NaN,NaN,Pune,Electronic Goods Manufacturers,Electronic Equipment Manufacturers,Show Number,WhatsApp,23 Years,in Business
2,https://www.justdial.com/Pune/Accurate-Industr...,"data:image/svg+xml,%3csvg%20xmlns=%27http://ww...",https://images.jdmagicbox.com/v2/comp/def_cont...,https://content.jdmagicbox.com/comp/pune/x3/02...,"data:image/svg+xml,%3csvg%20xmlns=%27http://ww...","data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP//...","data:image/svg+xml,%3csvg%20xmlns=%27http://ww...","data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP//...","data:image/svg+xml,%3csvg%20xmlns=%27http://ww...","data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP//...",...,126 Ratings,https://akam.cdn.jdmagicbox.com/images/iconten...,This business Information is verified by Justd...,Pune,Electronic Equipment Manufacturers,Control Panel Manufacturers,Show Number,WhatsApp,26 Years,in Business
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.justdial.com/Pune/Intelux-Electron...,"data:image/svg+xml,%3csvg%20xmlns=%27http://ww...",https://images.jdmagicbox.com/v2/comp/def_cont...,https://content.jdmagicbox.com/v2/comp/pune/x5...,"data:image/svg+xml,%3csvg%20xmlns=%27http://ww...","data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP//...","data:image/svg+xml,%3csvg%20xmlns=%27http://ww...","data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP//...","data:image/svg+xml,%3csvg%20xmlns=%27http://ww...","data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP//...",...,84 Ratings,https://akam.cdn.jdmagicbox.com/images/iconten...,This business Information is verified by Justd...,Pune,Isolation Transformer Manufacturers,Transformer Manufacturers,Show Number,WhatsApp,14 Years,in Business

In [ ]:
df1['company_name']

0      Cotmac Electronics Pvt Ltd (Corporate Office)
1                                  Smartline Systems
2               Accurate Industrial Controls Pvt Ltd
3                                                NaN
4                        Intelux Electronics Pvt Ltd
                           ...
120                Kyoritsu Electric (India) Pvt Ltd
121                                    Sivitek INDIA
122                          Sonic Multitech Pvt Ltd
123                    Yash Tech Electronics Pvt Ltd
124                               Global Engineering
Name: company_name, Length: 125, dtype: object

In [ ]:
df1.shape

(125, 25)

In [ ]:
df1.columns

Index(['business_url', 'placeholder_svg_image', 'default_category_image',
       'business_image', 'placeholder_image_1', 'placeholder_image_2',
       'placeholder_image_3', 'placeholder_image_4', 'placeholder_image_5',
       'placeholder_image_6', 'ui_element', 'ui_element_2', 'ui_element_3',
       'company_name', 'rating', 'rating_count', 'verified_icon',
       'verification_status', 'city', 'primary_category', 'secondary_category',
       'show_number_button', 'whatsapp_option', 'business_age',
       'business_age_label'],
      dtype='object')

In [ ]:

clean_df = df1[[
    'company_name',
    'business_url',
    'city',
    'primary_category',
    'secondary_category',
    'rating',
    'rating_count',
    'business_age',
    'business_age_label'
]]

# preview cleaned dataset
print(clean_df.head())

# dataset info
print("\nShape:", clean_df.shape)

                                    company_name  \
0  Cotmac Electronics Pvt Ltd (Corporate Office)
1                              Smartline Systems
2           Accurate Industrial Controls Pvt Ltd
3                                            NaN
4                    Intelux Electronics Pvt Ltd

                                        business_url  city  \
0  https://www.justdial.com/Pune/Cotmac-Electroni...  Pune
1  https://www.justdial.com/Pune/Smartline-System...  Pune
2  https://www.justdial.com/Pune/Accurate-Industr...  Pune
3                                                NaN   NaN
4  https://www.justdial.com/Pune/Intelux-Electron...  Pune

                      primary_category                  secondary_category  \
0         Electronic Equipment Dealers          CCTV Installation Services
1       Electronic Goods Manufacturers  Electronic Equipment Manufacturers
2   Electronic Equipment Manufacturers         Control Panel Manufacturers
3                                  NaN                                 NaN
4  Isolation Transformer Manufacturers           Transformer Manufacturers

   rating rating_count business_age business_age_label
0     4.1  281 Ratings          NaN                NaN
1     5.0  163 Ratings     23 Years        in Business
2     4.3  126 Ratings     26 Years        in Business
3     NaN          NaN          NaN                NaN
4     4.3   84 Ratings     14 Years        in Business

Shape: (125, 9)

In [ ]:
# keep only Pune companies

clean_df = clean_df[
    clean_df['city']
    .astype(str)
    .str.strip()
    .str.lower() == 'pune'
]

# reset index
clean_df = clean_df.reset_index(drop=True)

# preview
print(clean_df.head())

# total rows left
print("\nTotal Pune Companies:", clean_df.shape[0])

                                    company_name  \
0  Cotmac Electronics Pvt Ltd (Corporate Office)
1                              Smartline Systems
2           Accurate Industrial Controls Pvt Ltd
3                    Intelux Electronics Pvt Ltd
4                              Shree Engineering

                                        business_url  city  \
0  https://www.justdial.com/Pune/Cotmac-Electroni...  Pune
1  https://www.justdial.com/Pune/Smartline-System...  Pune
2  https://www.justdial.com/Pune/Accurate-Industr...  Pune
3  https://www.justdial.com/Pune/Intelux-Electron...  Pune
4  https://www.justdial.com/Pune/Shree-Engineerin...  Pune

                      primary_category                  secondary_category  \
0         Electronic Equipment Dealers          CCTV Installation Services
1       Electronic Goods Manufacturers  Electronic Equipment Manufacturers
2   Electronic Equipment Manufacturers         Control Panel Manufacturers
3  Isolation Transformer Manufacturers           Transformer Manufacturers
4                                  NaN                                 NaN

   rating rating_count business_age business_age_label
0     4.1  281 Ratings          NaN                NaN
1     5.0  163 Ratings     23 Years        in Business
2     4.3  126 Ratings     26 Years        in Business
3     4.3   84 Ratings     14 Years        in Business
4     4.3   76 Ratings     21 Years        in Business

Total Pune Companies: 70

In [ ]:
clean_df.head()

,company_name,business_url,city,primary_category,secondary_category,rating,rating_count,business_age,business_age_label
0,Cotmac Electronics Pvt Ltd (Corporate Office),https://www.justdial.com/Pune/Cotmac-Electroni...,Pune,Electronic Equipment Dealers,CCTV Installation Services,4.1,281 Ratings,NaN,NaN
1,Smartline Systems,https://www.justdial.com/Pune/Smartline-System...,Pune,Electronic Goods Manufacturers,Electronic Equipment Manufacturers,5.0,163 Ratings,23 Years,in Business
2,Accurate Industrial Controls Pvt Ltd,https://www.justdial.com/Pune/Accurate-Industr...,Pune,Electronic Equipment Manufacturers,Control Panel Manufacturers,4.3,126 Ratings,26 Years,in Business
3,Intelux Electronics Pvt Ltd,https://www.justdial.com/Pune/Intelux-Electron...,Pune,Isolation Transformer Manufacturers,Transformer Manufacturers,4.3,84 Ratings,14 Years,in Business
4,Shree Engineering,https://www.justdial.com/Pune/Shree-Engineerin...,Pune,NaN,NaN,4.3,76 Ratings,21 Years,in Business

In [ ]:
clean_df.dropna(inplace=True)

In [ ]:
clean_df.isnull().sum()

company_name          0
business_url          0
city                  0
primary_category      0
secondary_category    0
rating                0
rating_count          0
business_age          0
business_age_label    0
dtype: int64

In [ ]:
clean_df.duplicated().sum()

np.int64(13)

In [ ]:
clean_df.drop_duplicates(inplace=True)

In [ ]:
clean_df.duplicated().sum()

np.int64(0)

In [ ]:
clean_df.head(20)

,company_name,business_url,city,primary_category,secondary_category,rating,rating_count,business_age,business_age_label
1,Smartline Systems,https://www.justdial.com/Pune/Smartline-System...,Pune,Electronic Goods Manufacturers,Electronic Equipment Manufacturers,5.0,163 Ratings,23 Years,in Business
2,Accurate Industrial Controls Pvt Ltd,https://www.justdial.com/Pune/Accurate-Industr...,Pune,Electronic Equipment Manufacturers,Control Panel Manufacturers,4.3,126 Ratings,26 Years,in Business
3,Intelux Electronics Pvt Ltd,https://www.justdial.com/Pune/Intelux-Electron...,Pune,Isolation Transformer Manufacturers,Transformer Manufacturers,4.3,84 Ratings,14 Years,in Business
5,Technofour,https://www.justdial.com/Pune/Technofour-Near-...,Pune,Electronic Equipment Manufacturers,Conductivity Meter Manufacturers,4.2,47 Ratings,54 Years,in Business
8,Ul Electrodevices Pvt Ltd,https://www.justdial.com/Pune/Ul-Electrodevice...,Pune,Cable Harness Manufacturers,Electronic Equipment Manufacturers,3.8,26 Ratings,21 Years,in Business
9,Vinit Electronics & Electricals,https://www.justdial.com/Pune/Vinit-Electronic...,Pune,Electrical Equipment Manufacturers,Electronic Component Manufacturers,4.0,20 Ratings,35 Years,in Business
10,Power Formers Engineers Pvt Ltd,https://www.justdial.com/Pune/Power-Formers-En...,Pune,Electrical Control Panel Manufacturers,Electronic Equipment Manufacturers,4.7,17 Ratings,42 Years,in Business
11,Lenze Mechatronics Pvt Ltd,https://www.justdial.com/Pune/Lenze-Mechatroni...,Pune,Electronic Equipment Manufacturers,Electric Motor Dealers,4.3,16 Ratings,21 Years,in Business
12,Bharat Electrical Pvt Ltd,https://www.justdial.com/Pune/Bharat-Electrica...,Pune,Electronic Equipment Manufacturers,Wire Dealers,4.4,12 Ratings,14 Years,in Business
14,Minitronix Machines Pvt Ltd,https://www.justdial.com/Pune/Minitronix-Machi...,Pune,Electronic Equipment Manufacturers,Induction Heating Equipment Manufacturers,4.6,9 Ratings,22 Years,in Business
15,Mascot Industries,https://www.justdial.com/Pune/Mascot-Industrie...,Pune,Packaging Material Dealers,Electronic Equipment Manufacturers,3.7,10 Ratings,18 Years,in Business
16,Powertek,https://www.justdial.com/Pune/Powertek-Near-Pa...,Pune,SMPS Manufacturers,Electronic Equipment Manufacturers,4.7,7 Ratings,18 Years,in Business
19,Electronics Unlimited,https://www.justdial.com/Pune/Electronics-Unli...,Pune,Electronic Equipment Manufacturers,Switch Wholesalers,3.6,9 Ratings,21 Years,in Business
21,Concept Electronic Engineering Solution Pvt Ltd,https://www.justdial.com/Pune/Concept-Electron...,Pune,Electronic Goods Manufacturers,Cable Harness Manufacturers,3.8,6 Ratings,36 Years,in Business
22,Analogik Electronics Corporation,https://www.justdial.com/Pune/Analogik-Electro...,Pune,Electronic Equipment Manufacturers,Sensor Manufacturers,3.0,6 Ratings,32 Years,in Business
24,Asi Test Lab Pvt Ltd,https://www.justdial.com/Pune/Asi-Test-Lab-Pvt...,Pune,Electronic Component Manufacturers,Electronic Equipment Manufacturers,4.3,4 Ratings,30 Years,in Business
26,Zoroy Electronics Ltd,https://www.justdial.com/Pune/Zoroy-Electronic...,Pune,Electronic Component Manufacturers,Electronic Equipment Manufacturers,2.8,6 Ratings,7 Years,in Business
28,Allied Electronics Corpn,https://www.justdial.com/Pune/Allied-Electroni...,Pune,Electronic Equipment Manufacturers,Electrical Connector Dealers,4.6,3 Ratings,21 Years,in Business
35,Bevcon Wayors Pvt Ltd,https://www.justdial.com/Pune/Bevcon-Wayors-Pv...,Pune,Electronic Equipment Manufacturers,Construction Machine Dealers,3.4,4 Ratings,24 Years,in Business
36,Voltiza Power Technology,https://www.justdial.com/Pune/Voltiza-Power-Te...,Pune,Electronic Equipment Manufacturers,Electrical Panel Manufacturers,4.0,3 Ratings,8 Years,in Business

In [ ]:
clean_df1=clean_df

In [ ]:
clean_df1.to_csv("top_70_companies.csv", index=False)

In [ ]:
import pandas as pd

# load both csvs
df22 = pd.read_csv("/content/google.csv")
df3 = pd.read_csv("/content/google (1).csv")

# combine them
df2 = pd.concat([df22, df3], ignore_index=True)

# preview
print(df2.head())

# total rows
print("Total Rows:", df2.shape[0])

                                         hfpxzc href  \
0                                                NaN
1                                                NaN
2  https://www.google.com/maps/place/Thermo+Instr...
3  https://www.google.com/maps/place/Uni-Automati...
4  https://www.google.com/maps/place/Jaycee+Techn...

                                              qBF1Pd  MW4etd UY7F9  \
0                                                NaN     NaN   NaN
1                                                NaN     NaN   NaN
2  Thermo Instruments – Thermo couple,Rtd,Tempera...     5.0  (84)
3                       Uni-Automation (I) Pvt. Ltd.     4.8  (12)
4                        Jaycee Technologies Pvt Ltd     4.5  (26)

         W4Efsd W4Efsd 2                                           W4Efsd 3  \
0           NaN      NaN                                                NaN
1           NaN      NaN                                                NaN
2  Manufacturer        ·                        Shop No 13/4, Ellora Shopee
3  Manufacturer        ·  202 Vyankatesh Apartments opposite Patil Plaza...
4  Manufacturer        ·  Shed No. 7, Nanekar Industry Building Survey N...

  W4Efsd 4             W4Efsd 5 W4Efsd 6          UsdlK  \
0      NaN                  NaN      NaN            NaN
1      NaN                  NaN      NaN            NaN
2   Closed     · Opens 9 am Tue        ·   098604 11186
3   Closed    · Opens 10 am Tue        ·  020 2442 0890
4   Closed  · Opens 9:30 am Tue        ·   085549 82251

                         lcr4fd href Cw1rxd   R8c4Qb Cw1rxd 2    R8c4Qb 2  \
0                                NaN    NaN      NaN      NaN         NaN
1                                NaN    NaN      NaN      NaN         NaN
2  https://www.thermocouplesrtd.com/        Website          Directions
3      http://www.uniautomation.com/        Website          Directions
4            https://jayceetech.com/        Website          Directions

                                          Jn12ke src  \
0                                                NaN
1                                                NaN
2  https://ssl.gstatic.com/local/servicebusiness/...
3                                                NaN
4                                                NaN

                                       ah5Ghc doJOZc ah5Ghc 2
0                                         NaN    NaN      NaN
1                                         NaN    NaN      NaN
2  "Helpful Staff and good quality of sensor"    NaN      NaN
3                                         NaN    NaN      NaN
4                           In-store shopping    NaN      NaN
Total Rows: 202

In [ ]:
df2.describe()

           rating
count  194.000000
mean     4.552577
std      0.486521
min      1.000000
25%      4.325000
50%      4.600000
75%      4.900000
max      5.000000

In [ ]:
df2.head()

,hfpxzc href,qBF1Pd,MW4etd,UY7F9,W4Efsd,W4Efsd 2,W4Efsd 3,W4Efsd 4,W4Efsd 5,W4Efsd 6,UsdlK,lcr4fd href,Cw1rxd,R8c4Qb,Cw1rxd 2,R8c4Qb 2,Jn12ke src,ah5Ghc,doJOZc,ah5Ghc 2
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.google.com/maps/place/Thermo+Instr...,"Thermo Instruments – Thermo couple,Rtd,Tempera...",5.0,(84),Manufacturer,·,"Shop No 13/4, Ellora Shopee",Closed,· Opens 9 am Tue,·,098604 11186,https://www.thermocouplesrtd.com/,,Website,,Directions,https://ssl.gstatic.com/local/servicebusiness/...,"""Helpful Staff and good quality of sensor""",NaN,NaN
3,https://www.google.com/maps/place/Uni-Automati...,Uni-Automation (I) Pvt. Ltd.,4.8,(12),Manufacturer,·,202 Vyankatesh Apartments opposite Patil Plaza...,Closed,· Opens 10 am Tue,·,020 2442 0890,http://www.uniautomation.com/,,Website,,Directions,NaN,NaN,NaN,NaN
4,https://www.google.com/maps/place/Jaycee+Techn...,Jaycee Technologies Pvt Ltd,4.5,(26),Manufacturer,·,"Shed No. 7, Nanekar Industry Building Survey N...",Closed,· Opens 9:30 am Tue,·,085549 82251,https://jayceetech.com/,,Website,,Directions,NaN,In-store shopping,NaN,NaN

In [ ]:
df2 = df2.dropna(how='all')

KeyError: Index(['company_name'], dtype='object')

In [ ]:
df2.head()

,hfpxzc href,qBF1Pd,MW4etd,UY7F9,W4Efsd,W4Efsd 2,W4Efsd 3,W4Efsd 4,W4Efsd 5,W4Efsd 6,UsdlK,lcr4fd href,Cw1rxd,R8c4Qb,Cw1rxd 2,R8c4Qb 2,Jn12ke src,ah5Ghc,doJOZc,ah5Ghc 2
2,https://www.google.com/maps/place/Thermo+Instr...,"Thermo Instruments – Thermo couple,Rtd,Tempera...",5.0,(84),Manufacturer,·,"Shop No 13/4, Ellora Shopee",Closed,· Opens 9 am Tue,·,098604 11186,https://www.thermocouplesrtd.com/,,Website,,Directions,https://ssl.gstatic.com/local/servicebusiness/...,"""Helpful Staff and good quality of sensor""",NaN,NaN
3,https://www.google.com/maps/place/Uni-Automati...,Uni-Automation (I) Pvt. Ltd.,4.8,(12),Manufacturer,·,202 Vyankatesh Apartments opposite Patil Plaza...,Closed,· Opens 10 am Tue,·,020 2442 0890,http://www.uniautomation.com/,,Website,,Directions,NaN,NaN,NaN,NaN
4,https://www.google.com/maps/place/Jaycee+Techn...,Jaycee Technologies Pvt Ltd,4.5,(26),Manufacturer,·,"Shed No. 7, Nanekar Industry Building Survey N...",Closed,· Opens 9:30 am Tue,·,085549 82251,https://jayceetech.com/,,Website,,Directions,NaN,In-store shopping,NaN,NaN
5,https://www.google.com/maps/place/AM+Electroni...,AM Electronics – Electronic Components Store i...,4.8,(499),Electronic parts supplier,·,"1st floor, Bhavana, 105, Vishnu",Closed,· Opens 10 am Tue,·,070280 52537,https://www.amelectronics.in/,,Website,,Directions,https://ssl.gstatic.com/local/servicebusiness/...,"""Good quality",NaN,NaN
6,https://www.google.com/maps/place/Starrbot+Aut...,Starrbot Automations Pvt. Ltd. - Motion Sensor...,4.4,(110),Automation company,·,"5th Floor, DNK Capital, Office no, Katraj - Ko...",Closed,· Opens 9:30 am Tue,·,020 6766 8830,https://starrbot.com/,,Website,,Directions,NaN,On-site services,NaN,NaN

In [ ]:
df2.columns = [

    # Google Maps business listing URL
    'google_maps_link',

    # Company / business name
    'company_name',

    # Google rating
    'rating',

    # Number of reviews
    'review_count',

    # Business type/category
    'business_type',

    # separator dot
    'separator_1',

    # Address
    'address',

    # Open/closed status
    'business_status',

    # Opening timing
    'opening_time',

    # separator dot
    'separator_2',

    # Phone number
    'phone_number',

    # Official website
    'website',

    # Website button icon
    'website_icon',

    # Website text
    'website_text',

    # Direction button icon
    'direction_icon',

    # Direction text
    'direction_text',

    # Business category image/icon
    'category_icon',

    # Review snippet / customer highlight
    'review_snippet',

    # Extra metadata
    'extra_info_1',

    # Extra metadata
    'extra_info_2'
]

In [ ]:
df2.shape

(197, 20)

In [ ]:
df2.columns

Index(['google_maps_link', 'company_name', 'rating', 'review_count',
       'business_type', 'separator_1', 'address', 'business_status',
       'opening_time', 'separator_2', 'phone_number', 'website',
       'website_icon', 'website_text', 'direction_icon', 'direction_text',
       'category_icon', 'review_snippet', 'extra_info_1', 'extra_info_2'],
      dtype='object')

In [ ]:
df2.head()

,google_maps_link,company_name,rating,review_count,business_type,separator_1,address,business_status,opening_time,separator_2,phone_number,website,website_icon,website_text,direction_icon,direction_text,category_icon,review_snippet,extra_info_1,extra_info_2
2,https://www.google.com/maps/place/Thermo+Instr...,"Thermo Instruments – Thermo couple,Rtd,Tempera...",5.0,(84),Manufacturer,·,"Shop No 13/4, Ellora Shopee",Closed,· Opens 9 am Tue,·,098604 11186,https://www.thermocouplesrtd.com/,,Website,,Directions,https://ssl.gstatic.com/local/servicebusiness/...,"""Helpful Staff and good quality of sensor""",NaN,NaN
3,https://www.google.com/maps/place/Uni-Automati...,Uni-Automation (I) Pvt. Ltd.,4.8,(12),Manufacturer,·,202 Vyankatesh Apartments opposite Patil Plaza...,Closed,· Opens 10 am Tue,·,020 2442 0890,http://www.uniautomation.com/,,Website,,Directions,NaN,NaN,NaN,NaN
4,https://www.google.com/maps/place/Jaycee+Techn...,Jaycee Technologies Pvt Ltd,4.5,(26),Manufacturer,·,"Shed No. 7, Nanekar Industry Building Survey N...",Closed,· Opens 9:30 am Tue,·,085549 82251,https://jayceetech.com/,,Website,,Directions,NaN,In-store shopping,NaN,NaN
5,https://www.google.com/maps/place/AM+Electroni...,AM Electronics – Electronic Components Store i...,4.8,(499),Electronic parts supplier,·,"1st floor, Bhavana, 105, Vishnu",Closed,· Opens 10 am Tue,·,070280 52537,https://www.amelectronics.in/,,Website,,Directions,https://ssl.gstatic.com/local/servicebusiness/...,"""Good quality",NaN,NaN
6,https://www.google.com/maps/place/Starrbot+Aut...,Starrbot Automations Pvt. Ltd. - Motion Sensor...,4.4,(110),Automation company,·,"5th Floor, DNK Capital, Office no, Katraj - Ko...",Closed,· Opens 9:30 am Tue,·,020 6766 8830,https://starrbot.com/,,Website,,Directions,NaN,On-site services,NaN,NaN

In [ ]:
df2.head()

,google_maps_link,company_name,rating,review_count,business_type,separator_1,address,business_status,opening_time,separator_2,phone_number,website,website_button_icon,website_text,direction_button_icon,direction_text,category_icon,review_snippet
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.google.com/maps/place/Thermo+Instr...,"Thermo Instruments – Thermo couple,Rtd,Tempera...",5.0,(84),Manufacturer,·,"Shop No 13/4, Ellora Shopee",Closed,· Opens 9 am Tue,·,098604 11186,https://www.thermocouplesrtd.com/,,Website,,Directions,https://ssl.gstatic.com/local/servicebusiness/...,"""Helpful Staff and good quality of sensor"""
3,https://www.google.com/maps/place/Uni-Automati...,Uni-Automation (I) Pvt. Ltd.,4.8,(12),Manufacturer,·,202 Vyankatesh Apartments opposite Patil Plaza...,Closed,· Opens 10 am Tue,·,020 2442 0890,http://www.uniautomation.com/,,Website,,Directions,NaN,NaN
4,https://www.google.com/maps/place/Jaycee+Techn...,Jaycee Technologies Pvt Ltd,4.5,(26),Manufacturer,·,"Shed No. 7, Nanekar Industry Building Survey N...",Closed,· Opens 9:30 am Tue,·,085549 82251,https://jayceetech.com/,,Website,,Directions,NaN,In-store shopping

In [ ]:
clean_df2 = df2[[
    'company_name',
    'business_type',
    'address',
    'phone_number',
    'website',
    'rating',
    'review_count',
    'review_snippet',
    'opening_time',
    'google_maps_link',
]]

In [ ]:
clean_df2 = clean_df2.dropna(subset=['company_name', 'website'])

In [ ]:
clean_df2.head()

,company_name,business_type,address,phone_number,website,rating,review_count,review_snippet,opening_time,google_maps_link
2,"Thermo Instruments – Thermo couple,Rtd,Tempera...",Manufacturer,"Shop No 13/4, Ellora Shopee",098604 11186,https://www.thermocouplesrtd.com/,5.0,(84),"""Helpful Staff and good quality of sensor""",· Opens 9 am Tue,https://www.google.com/maps/place/Thermo+Instr...
3,Uni-Automation (I) Pvt. Ltd.,Manufacturer,202 Vyankatesh Apartments opposite Patil Plaza...,020 2442 0890,http://www.uniautomation.com/,4.8,(12),NaN,· Opens 10 am Tue,https://www.google.com/maps/place/Uni-Automati...
4,Jaycee Technologies Pvt Ltd,Manufacturer,"Shed No. 7, Nanekar Industry Building Survey N...",085549 82251,https://jayceetech.com/,4.5,(26),In-store shopping,· Opens 9:30 am Tue,https://www.google.com/maps/place/Jaycee+Techn...
5,AM Electronics – Electronic Components Store i...,Electronic parts supplier,"1st floor, Bhavana, 105, Vishnu",070280 52537,https://www.amelectronics.in/,4.8,(499),"""Good quality",· Opens 10 am Tue,https://www.google.com/maps/place/AM+Electroni...
6,Starrbot Automations Pvt. Ltd. - Motion Sensor...,Automation company,"5th Floor, DNK Capital, Office no, Katraj - Ko...",020 6766 8830,https://starrbot.com/,4.4,(110),On-site services,· Opens 9:30 am Tue,https://www.google.com/maps/place/Starrbot+Aut...

In [ ]:
clean_df2.shape

(186, 10)

In [ ]:
keywords = [
    'manufacturer',
    'automation',
    'instrumentation',
    'industrial',
    'electronics'
]

pattern = '|'.join(keywords)

filtered_df = clean_df2[
    clean_df2['business_type']
    .astype(str)
    .str.lower()
    .str.contains(pattern, na=False)
]

In [ ]:
bad_keywords = [
    'dealer',
    'supplier',
    'shop',
    'repair',
    'cctv',
    'service'
]

bad_pattern = '|'.join(bad_keywords)

clean_df2 = filtered_df[
    ~filtered_df['business_type']
    .astype(str)
    .str.lower()
    .str.contains(bad_pattern, na=False)
]

In [ ]:
clean_df2.shape

(121, 10)

In [ ]:
clean_df2 = clean_df2.drop_duplicates(
    subset='company_name'
)

In [ ]:
clean_df2['review_count_num'] = (
    clean_df2['review_count']
    .astype(str)
    .str.replace(r'[^0-9]', '', regex=True)
)

clean_df2['review_count_num'] = pd.to_numeric(
    clean_df2['review_count_num'],
    errors='coerce'
)

In [ ]:
top_df = clean_df2.sort_values(
    by=['review_count_num', 'rating'],
    ascending=False
)

In [ ]:
top_100 = top_df.head(100)

In [ ]:
top_100.to_csv("top_100_companies.csv", index=False)